### ISSUE TITLE
about ImageSet256  ImageSetV4 ImageSet2

### ISSUE THREAD

**Issue by caoyifeng001** [intrepidChw/ASAP-Net#1]
hi thank open great job,
please share  ImageSet256  ImageSetV4 ImageSet2 file .

**Comment by hwcao17** [comment]
Sorry for the late reply. Only ImageSet2 is needed actually and it contains dataset split information same with the split in semanticKITTI paper. I have uploaded it. Please check the README to put it under your dataset folder.
